/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    leads: Lead;
    products: Product;
    orders: Order;
    analytics: Analytics;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * User management and access control
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  role: 'superadmin' | 'admin' | 'manager' | 'user';
  department?: ('executive' | 'sales' | 'marketing' | 'operations' | 'legal' | 'customer_service') | null;
  permissions?:
    | {
        resource?: ('all' | 'leads' | 'analytics' | 'email' | 'financial' | 'users' | 'settings') | null;
        actions?:
          | {
              action?: ('create' | 'read' | 'update' | 'delete' | 'export') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  lastLogin?: string | null;
  loginCount?: number | null;
  isActive?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Lead management and analytics dashboard - Visit /admin/dashboard for detailed analytics
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  email: string;
  first: string;
  last: string;
  phone?: string | null;
  street?: string | null;
  city?: string | null;
  state?: string | null;
  zipCode?: string | null;
  convictionType?:
    | (
        | 'DUI'
        | 'felony'
        | 'misdemeanor'
        | 'drug-possession'
        | 'theft'
        | 'domestic-violence'
        | 'assault'
        | 'other'
        | 'not-sure'
      )
    | null;
  convictionYear?: string | null;
  urgency?: ('immediate' | 'within-month' | 'within-3months' | 'within-year' | 'just-exploring') | null;
  budget?: ('under-100' | '100-500' | '500-1000' | '1000-2000' | 'over-2000' | 'flexible') | null;
  previousAttempts?: ('never' | 'tried-myself' | 'hired-lawyer' | 'partial-success') | null;
  interests?: string | null;
  employmentGoals?: string | null;
  /**
   * Automatically calculated lead score
   */
  leadScore?: number | null;
  leadSegment?: ('hot' | 'warm' | 'lukewarm' | 'cold') | null;
  emailSequence?:
    | (
        | 'general-nurture'
        | 'dui-specific'
        | 'misdemeanor-specific'
        | 'consultation-follow-up'
        | 'high-intent-acceleration'
      )
    | null;
  leadMagnet?: string | null;
  referrer?: string | null;
  amount?: number | null;
  paid?: boolean | null;
  stripeSessionId?: string | null;
  lookup?: boolean | null;
  fullService?: boolean | null;
  source?: ('organic' | 'paid' | 'referral' | 'direct' | 'social' | 'email') | null;
  /**
   * Marketing campaign identifier
   */
  utmCampaign?: string | null;
  /**
   * Traffic source (google, facebook, etc.)
   */
  utmSource?: string | null;
  /**
   * Marketing medium (cpc, email, social, etc.)
   */
  utmMedium?: string | null;
  conversionStage?: ('lead' | 'diy_purchased' | 'review_upgrade' | 'full_service') | null;
  /**
   * When the $50 DIY package was purchased
   */
  diyPurchaseDate?: string | null;
  /**
   * When they upgraded to review or full service
   */
  upgradeDate?: string | null;
  upgradeType?: ('none' | 'review' | 'full') | null;
  /**
   * Minutes from DIY purchase to upgrade
   */
  timeToUpgrade?: number | null;
  /**
   * Sum of all purchases from this lead
   */
  totalRevenue?: number | null;
  /**
   * Projected total value of this customer
   */
  lifetimeValue?: number | null;
  emailStatus?: ('not_sent' | 'sent' | 'delivered' | 'failed') | null;
  /**
   * When the last email was sent to this lead
   */
  lastEmailSent?: string | null;
  /**
   * Count of emails sent to this lead
   */
  emailsSent?: number | null;
  /**
   * How long they spent on the website before converting
   */
  timeOnSite?: string | null;
  /**
   * Number of pages viewed before converting
   */
  pagesViewed?: number | null;
  /**
   * Device used for conversion
   */
  deviceType?: ('desktop' | 'mobile' | 'tablet') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * Product name/title
   */
  name: string;
  /**
   * URL-friendly product identifier
   */
  slug: string;
  /**
   * Detailed product description
   */
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Brief product summary (max 300 chars)
   */
  shortDescription?: string | null;
  category: 'diy' | 'legal' | 'consultation' | 'express' | 'review';
  serviceType: 'digital' | 'service' | 'consultation' | 'full_service';
  /**
   * Price in USD
   */
  price: number;
  /**
   * Original price (for showing discounts)
   */
  originalPrice?: number | null;
  /**
   * Stripe Price ID for payments
   */
  stripePriceId?: string | null;
  /**
   * Stripe Product ID
   */
  stripeProductId?: string | null;
  status: 'active' | 'inactive' | 'draft' | 'archived';
  inventory?: {
    trackInventory?: boolean | null;
    quantity?: number | null;
    lowStockThreshold?: number | null;
    allowBackorders?: boolean | null;
  };
  processingTime?: {
    /**
     * Minimum processing days
     */
    minDays?: number | null;
    /**
     * Maximum processing days
     */
    maxDays?: number | null;
    businessDaysOnly?: boolean | null;
  };
  /**
   * Types of convictions this service covers
   */
  convictionTypes?:
    | ('felony' | 'misdemeanor' | 'infraction' | 'juvenile' | 'dui' | 'drug' | 'violent' | 'white_collar')[]
    | null;
  /**
   * Key features and benefits
   */
  features?:
    | {
        feature: string;
        description?: string | null;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Requirements for this service
   */
  requirements?:
    | {
        requirement: string;
        required?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Frequently asked questions
   */
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  images?:
    | {
        image: string | Media;
        alt: string;
        isPrimary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Downloadable documents (for digital products)
   */
  documents?:
    | {
        document: string | Media;
        title: string;
        description?: string | null;
        downloadable?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Product performance metrics
   */
  analytics?: {
    views?: number | null;
    totalSales?: number | null;
    revenue?: number | null;
    /**
     * Conversion rate percentage
     */
    conversionRate?: number | null;
    averageRating?: number | null;
    totalReviews?: number | null;
  };
  /**
   * Show on homepage and featured sections
   */
  featured?: boolean | null;
  /**
   * Mark as popular choice
   */
  popular?: boolean | null;
  /**
   * Mark as best value option
   */
  bestValue?: boolean | null;
  tags?:
    | (
        | 'california'
        | 'los_angeles'
        | 'orange_county'
        | 'san_francisco'
        | 'san_diego'
        | 'expungement'
        | 'record_sealing'
        | 'prop_47'
        | 'prop_64'
        | 'fast_track'
        | 'attorney_review'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Unique order identifier
   */
  orderNumber: string;
  status:
    | 'pending'
    | 'processing'
    | 'review'
    | 'filing'
    | 'court_processing'
    | 'completed'
    | 'cancelled'
    | 'refunded'
    | 'on_hold';
  customer: {
    firstName: string;
    lastName: string;
    email: string;
    phone?: string | null;
    address?: {
      street?: string | null;
      city?: string | null;
      state?: string | null;
      zipCode?: string | null;
    };
  };
  items: {
    product: string | Product;
    quantity: number;
    /**
     * Price at time of purchase
     */
    price: number;
    /**
     * Line item total (quantity × price)
     */
    total: number;
    id?: string | null;
  }[];
  totals: {
    subtotal: number;
    tax?: number | null;
    discount?: number | null;
    total: number;
  };
  payment?: {
    method?: ('credit_card' | 'paypal' | 'bank_transfer' | 'check') | null;
    status?: ('pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'partial_refund') | null;
    /**
     * Payment processor transaction ID
     */
    transactionId?: string | null;
    /**
     * Stripe Payment Intent ID
     */
    stripePaymentIntentId?: string | null;
    paidAt?: string | null;
    refundAmount?: number | null;
    refundReason?: string | null;
  };
  /**
   * Legal case information
   */
  caseDetails?: {
    /**
     * Court case number
     */
    caseNumber?: string | null;
    /**
     * Court where case was filed
     */
    court?: string | null;
    county?:
      | (
          | 'los_angeles'
          | 'orange'
          | 'san_diego'
          | 'riverside'
          | 'san_bernardino'
          | 'ventura'
          | 'santa_barbara'
          | 'kern'
          | 'fresno'
          | 'other'
        )
      | null;
    convictionDate?: string | null;
    convictionType?: ('felony' | 'misdemeanor' | 'infraction' | 'juvenile' | 'dui' | 'drug')[] | null;
    charges?:
      | {
          charge: string;
          /**
           * Penal code section
           */
          code?: string | null;
          /**
           * Final disposition of charge
           */
          disposition?: string | null;
          id?: string | null;
        }[]
      | null;
    documents?:
      | {
          document: string | Media;
          type?: ('court_records' | 'id_copy' | 'fingerprint' | 'probation' | 'other') | null;
          description?: string | null;
          uploadedAt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Case progress timeline
   */
  timeline?:
    | {
        date: string;
        status: string;
        description: string;
        /**
         * Internal note (not visible to customer)
         */
        internal?: boolean | null;
        /**
         * Staff member who made the update
         */
        updatedBy?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Staff assignment
   */
  assignedTo?: {
    /**
     * Assigned attorney
     */
    attorney?: string | null;
    /**
     * Assigned paralegal
     */
    paralegal?: string | null;
    /**
     * Assigned case manager
     */
    caseManager?: string | null;
  };
  /**
   * Customer communications log
   */
  communications?:
    | {
        date: string;
        type: 'email' | 'phone' | 'sms' | 'mail' | 'in_person';
        direction: 'inbound' | 'outbound';
        subject?: string | null;
        content: string;
        /**
         * Staff member who handled communication
         */
        staffMember?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Expected completion date
   */
  expectedCompletion?: string | null;
  /**
   * Actual completion date
   */
  actualCompletion?: string | null;
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  tags?: ('rush' | 'vip' | 'complex' | 'prop_47' | 'prop_64' | 'repeat' | 'referral')[] | null;
  /**
   * Internal notes
   */
  notes?:
    | {
        date: string;
        note: string;
        author: string;
        type?: ('general' | 'legal' | 'customer_service' | 'billing' | 'technical') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * How customer found us
   */
  source?:
    | ('website' | 'google' | 'facebook' | 'instagram' | 'referral' | 'repeat' | 'attorney_referral' | 'other')
    | null;
  /**
   * Promotional code used
   */
  promoCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: string;
  /**
   * Type of analytics event
   */
  eventType:
    | 'sale_completed'
    | 'payment_received'
    | 'refund_processed'
    | 'subscription_started'
    | 'subscription_cancelled'
    | 'lead_created'
    | 'customer_registered'
    | 'customer_login'
    | 'profile_updated'
    | 'product_viewed'
    | 'cart_add'
    | 'cart_remove'
    | 'checkout_started'
    | 'checkout_completed'
    | 'checkout_abandoned'
    | 'email_opened'
    | 'email_clicked'
    | 'ad_clicked'
    | 'social_share'
    | 'referral_made'
    | 'page_view'
    | 'search_performed'
    | 'form_submitted'
    | 'download_started'
    | 'error_occurred';
  /**
   * Source of the event
   */
  source:
    | 'website'
    | 'mobile_app'
    | 'api'
    | 'admin'
    | 'email'
    | 'social'
    | 'google_ads'
    | 'facebook_ads'
    | 'referral'
    | 'direct'
    | 'telegram'
    | 'system';
  /**
   * Event category for grouping
   */
  category?: ('revenue' | 'customer' | 'product' | 'marketing' | 'system' | 'legal' | 'support') | null;
  /**
   * Numeric value (revenue, quantity, etc.)
   */
  value?: number | null;
  /**
   * Currency code for monetary values
   */
  currency?: string | null;
  /**
   * Associated user ID
   */
  userId?: string | null;
  /**
   * Session identifier
   */
  sessionId?: string | null;
  /**
   * Related object reference
   */
  relatedObject?: {
    type?: ('product' | 'order' | 'lead' | 'user' | 'page' | 'email_campaign') | null;
    /**
     * ID of related object
     */
    id?: string | null;
    /**
     * Name/title of related object
     */
    name?: string | null;
  };
  /**
   * Additional event properties (JSON)
   */
  properties?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Event metadata and context
   */
  metadata?: {
    /**
     * User agent string
     */
    userAgent?: string | null;
    /**
     * IP address (anonymized)
     */
    ipAddress?: string | null;
    /**
     * Referrer URL
     */
    referrer?: string | null;
    /**
     * Current page URL
     */
    url?: string | null;
    /**
     * UTM source parameter
     */
    utmSource?: string | null;
    /**
     * UTM medium parameter
     */
    utmMedium?: string | null;
    /**
     * UTM campaign parameter
     */
    utmCampaign?: string | null;
    /**
     * UTM term parameter
     */
    utmTerm?: string | null;
    /**
     * UTM content parameter
     */
    utmContent?: string | null;
    device?: ('desktop' | 'mobile' | 'tablet' | 'unknown') | null;
    /**
     * Browser name and version
     */
    browser?: string | null;
    /**
     * Operating system
     */
    os?: string | null;
    location?: {
      country?: string | null;
      state?: string | null;
      city?: string | null;
      zipCode?: string | null;
    };
  };
  /**
   * Performance metrics
   */
  performance?: {
    /**
     * Page load time in milliseconds
     */
    pageLoadTime?: number | null;
    /**
     * Processing time in milliseconds
     */
    processingTime?: number | null;
    /**
     * Response time in milliseconds
     */
    responseTime?: number | null;
  };
  /**
   * Event tags for filtering and analysis
   */
  tags?:
    | (
        | 'ab_test'
        | 'high_value'
        | 'new_customer'
        | 'returning_customer'
        | 'mobile'
        | 'desktop'
        | 'conversion'
        | 'abandonment'
        | 'error'
        | 'success'
      )[]
    | null;
  /**
   * Has this event been processed by analytics systems?
   */
  isProcessed?: boolean | null;
  /**
   * When the event was processed
   */
  processedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'analytics';
        value: string | Analytics;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  department?: T;
  permissions?:
    | T
    | {
        resource?: T;
        actions?:
          | T
          | {
              action?: T;
              id?: T;
            };
        id?: T;
      };
  lastLogin?: T;
  loginCount?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  email?: T;
  first?: T;
  last?: T;
  phone?: T;
  street?: T;
  city?: T;
  state?: T;
  zipCode?: T;
  convictionType?: T;
  convictionYear?: T;
  urgency?: T;
  budget?: T;
  previousAttempts?: T;
  interests?: T;
  employmentGoals?: T;
  leadScore?: T;
  leadSegment?: T;
  emailSequence?: T;
  leadMagnet?: T;
  referrer?: T;
  amount?: T;
  paid?: T;
  stripeSessionId?: T;
  lookup?: T;
  fullService?: T;
  source?: T;
  utmCampaign?: T;
  utmSource?: T;
  utmMedium?: T;
  conversionStage?: T;
  diyPurchaseDate?: T;
  upgradeDate?: T;
  upgradeType?: T;
  timeToUpgrade?: T;
  totalRevenue?: T;
  lifetimeValue?: T;
  emailStatus?: T;
  lastEmailSent?: T;
  emailsSent?: T;
  timeOnSite?: T;
  pagesViewed?: T;
  deviceType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  category?: T;
  serviceType?: T;
  price?: T;
  originalPrice?: T;
  stripePriceId?: T;
  stripeProductId?: T;
  status?: T;
  inventory?:
    | T
    | {
        trackInventory?: T;
        quantity?: T;
        lowStockThreshold?: T;
        allowBackorders?: T;
      };
  processingTime?:
    | T
    | {
        minDays?: T;
        maxDays?: T;
        businessDaysOnly?: T;
      };
  convictionTypes?: T;
  features?:
    | T
    | {
        feature?: T;
        description?: T;
        highlight?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        requirement?: T;
        required?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        isPrimary?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        document?: T;
        title?: T;
        description?: T;
        downloadable?: T;
        id?: T;
      };
  analytics?:
    | T
    | {
        views?: T;
        totalSales?: T;
        revenue?: T;
        conversionRate?: T;
        averageRating?: T;
        totalReviews?: T;
      };
  featured?: T;
  popular?: T;
  bestValue?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              state?: T;
              zipCode?: T;
            };
      };
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        price?: T;
        total?: T;
        id?: T;
      };
  totals?:
    | T
    | {
        subtotal?: T;
        tax?: T;
        discount?: T;
        total?: T;
      };
  payment?:
    | T
    | {
        method?: T;
        status?: T;
        transactionId?: T;
        stripePaymentIntentId?: T;
        paidAt?: T;
        refundAmount?: T;
        refundReason?: T;
      };
  caseDetails?:
    | T
    | {
        caseNumber?: T;
        court?: T;
        county?: T;
        convictionDate?: T;
        convictionType?: T;
        charges?:
          | T
          | {
              charge?: T;
              code?: T;
              disposition?: T;
              id?: T;
            };
        documents?:
          | T
          | {
              document?: T;
              type?: T;
              description?: T;
              uploadedAt?: T;
              id?: T;
            };
      };
  timeline?:
    | T
    | {
        date?: T;
        status?: T;
        description?: T;
        internal?: T;
        updatedBy?: T;
        id?: T;
      };
  assignedTo?:
    | T
    | {
        attorney?: T;
        paralegal?: T;
        caseManager?: T;
      };
  communications?:
    | T
    | {
        date?: T;
        type?: T;
        direction?: T;
        subject?: T;
        content?: T;
        staffMember?: T;
        id?: T;
      };
  expectedCompletion?: T;
  actualCompletion?: T;
  priority?: T;
  tags?: T;
  notes?:
    | T
    | {
        date?: T;
        note?: T;
        author?: T;
        type?: T;
        id?: T;
      };
  source?: T;
  promoCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  eventType?: T;
  source?: T;
  category?: T;
  value?: T;
  currency?: T;
  userId?: T;
  sessionId?: T;
  relatedObject?:
    | T
    | {
        type?: T;
        id?: T;
        name?: T;
      };
  properties?: T;
  metadata?:
    | T
    | {
        userAgent?: T;
        ipAddress?: T;
        referrer?: T;
        url?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        device?: T;
        browser?: T;
        os?: T;
        location?:
          | T
          | {
              country?: T;
              state?: T;
              city?: T;
              zipCode?: T;
            };
      };
  performance?:
    | T
    | {
        pageLoadTime?: T;
        processingTime?: T;
        responseTime?: T;
      };
  tags?: T;
  isProcessed?: T;
  processedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  siteName: string;
  siteDescription?: string | null;
  contactInfo: {
    email: string;
    phone?: string | null;
    address?: string | null;
  };
  businessSettings?: {
    /**
     * Tax rate (e.g., 0.0875 for 8.75%)
     */
    taxRate?: number | null;
    currency?: ('USD' | 'EUR' | 'GBP') | null;
    timezone?: ('America/Los_Angeles' | 'America/Denver' | 'America/Chicago' | 'America/New_York') | null;
  };
  emailSettings: {
    fromName?: string | null;
    fromEmail: string;
    replyToEmail?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  businessSettings?:
    | T
    | {
        taxRate?: T;
        currency?: T;
        timezone?: T;
      };
  emailSettings?:
    | T
    | {
        fromName?: T;
        fromEmail?: T;
        replyToEmail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}